-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  game text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null,
  lines integer not null,
  level integer not null,
  created_at timestamptz not null default now()
);

create index if not exists scores_game_score_idx
  on public.scores (game, score desc, created_at desc);

alter table public.profiles enable row level security;
alter table public.scores enable row level security;

-- Public read access (leaderboards are public).
drop policy if exists "profiles: public read" on public.profiles;
create policy "profiles: public read"
  on public.profiles
  for select
  using (true);

drop policy if exists "scores: public read" on public.scores;
create policy "scores: public read"
  on public.scores
  for select
  using (true);

-- Only the logged-in user can write their own profile row.
drop policy if exists "profiles: self upsert" on public.profiles;
create policy "profiles: self upsert"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles: self update" on public.profiles;
create policy "profiles: self update"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Only logged-in users can submit scores for themselves.
drop policy if exists "scores: self insert" on public.scores;
create policy "scores: self insert"
  on public.scores
  for insert
  to authenticated
  with check (auth.uid() = user_id);

