-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  game text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null,
  lines integer not null,
  level integer not null,
  created_at timestamptz not null default now()
);

create index if not exists scores_game_score_idx
  on public.scores (game, score desc, created_at desc);

alter table public.profiles enable row level security;
alter table public.scores enable row level security;

-- Feature requests board (Arcade hub).
create table if not exists public.arcade_admins (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.feature_requests (
  id bigint generated by default as identity primary key,
  game text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  status text not null default 'open', -- open | accepted | rejected | implemented
  created_at timestamptz not null default now()
);

create table if not exists public.feature_request_votes (
  request_id bigint not null references public.feature_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, user_id)
);

create index if not exists feature_requests_game_status_created_idx
  on public.feature_requests (game, status, created_at desc);

create index if not exists feature_request_votes_request_idx
  on public.feature_request_votes (request_id);

alter table public.arcade_admins enable row level security;
alter table public.feature_requests enable row level security;
alter table public.feature_request_votes enable row level security;

-- Public read access (leaderboards are public).
drop policy if exists "profiles: public read" on public.profiles;
create policy "profiles: public read"
  on public.profiles
  for select
  using (true);

drop policy if exists "scores: public read" on public.scores;
create policy "scores: public read"
  on public.scores
  for select
  using (true);

drop policy if exists "admins: public read" on public.arcade_admins;
create policy "admins: public read"
  on public.arcade_admins
  for select
  using (true);

drop policy if exists "feature_requests: public read" on public.feature_requests;
create policy "feature_requests: public read"
  on public.feature_requests
  for select
  using (true);

drop policy if exists "feature_votes: public read" on public.feature_request_votes;
create policy "feature_votes: public read"
  on public.feature_request_votes
  for select
  using (true);

-- Only the logged-in user can write their own profile row.
drop policy if exists "profiles: self upsert" on public.profiles;
create policy "profiles: self upsert"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles: self update" on public.profiles;
create policy "profiles: self update"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Only logged-in users can submit scores for themselves.
drop policy if exists "scores: self insert" on public.scores;
create policy "scores: self insert"
  on public.scores
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Requests: authenticated users can create their own.
drop policy if exists "feature_requests: self insert" on public.feature_requests;
create policy "feature_requests: self insert"
  on public.feature_requests
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Votes: authenticated users can vote once per request (pk enforces uniqueness).
drop policy if exists "feature_votes: self insert" on public.feature_request_votes;
create policy "feature_votes: self insert"
  on public.feature_request_votes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "feature_votes: self delete" on public.feature_request_votes;
create policy "feature_votes: self delete"
  on public.feature_request_votes
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- Status updates: only admins can update.
drop policy if exists "feature_requests: admin update" on public.feature_requests;
create policy "feature_requests: admin update"
  on public.feature_requests
  for update
  to authenticated
  using (exists (select 1 from public.arcade_admins a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.arcade_admins a where a.user_id = auth.uid()));
